server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ilyaselammary/spring-petclinic-migration/tree/main/petclinic-config
          default-label: main
          clone-on-start: true
