server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VOTRE_USERNAME/petclinic-config
          default-label: main
          clone-on-start: true
