server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: owners-service
          uri: lb://owners-service
          predicates:
            - Path=/api/owners/**
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vets/**
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visits/**
