server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vets/**
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visits/**
        - id: petclinic-monolith
          uri: lb://petclinic-monolith
          predicates:
            - Path=/**
