# Common configuration shared by all applications
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  messages:
    basename: messages/messages

logging:
  level:
    org.springframework: INFO
    org.springframework.samples.petclinic: INFO
